### ISSUE TITLE
Ratings Field adjustment

### ISSUE THREAD

**Issue by ykahan** [Compuskills-Jerusalem/shuk-routing#17]
@ShmielB 

I think that, since we've decided that the Ratings field of the CommoditiesStalls table should limit valid entries to the integers 1, 2, 3, 4, 5, then the UI should also only allow the user to enter those numbers.  No ratings of 0 or less, 6 or more, or decimal numbers like 1.4 or 2.32

**Comment by ShmielB** [comment]
Changed the ratings field ,
 Thanks @ykahan .
