### ISSUE TITLE
CommoditiesStalls table has pluralization wrongly on PK / FK

### ISSUE THREAD

**Issue by ttafet** [Compuskills-Jerusalem/shuk-routing#18]
![image](https://user-images.githubusercontent.com/7382006/42956300-5738a72a-8b88-11e8-9a90-cce7e93bef02.png)

**Comment by ShmielB** [comment]
@ttafet  @ykahan  @ykosbie  @chefaharon  @hershyd  

I fixed the problem with the pluralization on the online DataBase .

**Comment by ShmielB** [comment]
@ttafet @ykahan @ykosbie @chefaharon @hershyd
**Sorry i made a mistake just one person has to run it to update the online Data Base .**
