### ISSUE TITLE
Stall ID / Commodity ID  on add commodity stall view

### ISSUE THREAD

**Issue by ShmielB** [Compuskills-Jerusalem/shuk-routing#19]
### We shouldn't need to specify the Stall id /Commodity ID , just the Stall name and commodity  name .

**Comment by ykopstein** [comment]
@ShmielB what if the end user wants to add a stall that's not already in the DB?  What kind of UI are you thinking about?

**Comment by ShmielB** [comment]
As we discussed in #13  and #22 and in #3   we should have a combo box so if the sall or  the commodity is not in the drop down they should be able to type it .
