### ISSUE TITLE
About ShukRoutingDB

### ISSUE THREAD

**Issue by hershyd** [Compuskills-Jerusalem/shuk-routing#2]
HI Yehoshua, The Database Looks Good, But About The ID's In The Database It Seems Not Working With "Entity Framework" Convention,
If Its Possible To Change ALL The ID's in The Database To (For Example: CommodityID ) And Also In The Joint Table,

Thanks

**Comment by ykahan** [comment]
Taken care of.

**Comment by ykahan** [comment]
Really done this time.  I think.
